FROM python:3.12-slim

WORKDIR /app

# dipendneze
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    gcc \
    curl \
    iptables \
    sqlite3 \
    && rm -rf /var/lib/apt/lists/*

# installazione uv 
COPY --from=ghcr.io/astral-sh/uv:latest /uv /usr/local/bin/uv

COPY pyproject.toml uv.lock ./

# installazione dipendenze
RUN uv sync --frozen --no-dev

# copia codice sorgente
COPY src/ ./src/

# creazione directory per i dati
RUN mkdir -p /app/data

# esporre porta http(verrà configurato dalle variabili di ambiente)
EXPOSE 8000

CMD ["uv", "run", "python", "-m", "src.node.main"]